source: site
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: pages
collections_config: {}
_inputs: {}
_select_data: {}
_structures:
  content_blocks:
    style: select
    id_key: _bookshop_name
    values:
      - value:
          _bookshop_name: hero
          text: Hello World!
        label: Hero
        description:
        icon:
        tags: []
        _inputs: {}
      - value:
          _bookshop_name: sample
          text: Hello World!
        label: Sample
        description:
        icon:
        tags: []
        _inputs: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
