# ALL EDITING FUNCTIONALITIES HERE

backend:
  name: git-gateway #can be changed depending on authentication git-gateway supports non github users

collections: 
  - name: "testimonials"
    label: "Testimonials"
    folder: "src/testimonials"
    create: true
    slug: "{{ slug }}"
    fields:
      - {
        label: "Title", 
        name: "title",
        widget: "string"
      }
      - {
        label: "Publish Date",
        name: "date",
        widget: "datetime"
      }
      - {
        label: "Author", 
        name: "author",
        widget: "string"
      }
      - {
        label: "Position", 
        name: "position",
        widget: "string",
        required: false
      }
      - {
        label: "Content",
        name: "body",
        widget: "markdown"
      }
      

media_folder: "assets/img" #wehre media files are stored